### ISSUE TITLE
Issue with GPU0 calulation

### ISSUE THREAD

**Issue by xnetproject** [sp-hash/SPMiner#1]
Verified GPU0 Calculation shows hashrate in Mh/s for Nvidia gpus. GPU1 shows the correct expected calculation based on verthash mining,.

This does not register hashrate properly.

this is for version spminer1-fix13

![Capture](https://user-images.githubusercontent.com/83045138/115798919-0096ae00-a39d-11eb-8914-4a5870050b10.PNG)

**Comment by sp-hash** [comment]
This build need compute 6.1 or better and failing on the latest rtx models. You should upgrade to #3
